<?php require 'templates/partials/header.phtml'; ?>

<form method="post" action="<?= $action === 'create-category' ? $action : $action . (isset($category) && isset($category->category_id) ? '?category_id=' . $category->category_id : '') ?>" class="form-container">
    <label for="category">Category</label>
    <input type="text" name="category" id="category" value="<?= isset($category) && isset($category->category) ? $category->category : '' ?>">
    <button type="submit">Submit category</button>
</form>

<?php require 'templates/partials/footer.phtml'; ?>
