<?php require 'templates/partials/header.phtml' ?>


<div class="mt-5 w-25 mx-auto pt-4">
    <form method="POST" action="auth">
    <div class="container text-white p-5">
        <style>
            .container {
            background-color: #040431;
            }
        </style>
        <div class="text-center">
            <h2 class="text-white mt-2">LOGIN</h2>
        </div>
        <div class="form-group">
            <label for="user_name" class="mt-3">Usuario:</label>
            <input type="user_name" required class="form-control" id="user_name" name="user_name" aria-describedby="usernameHelp">
        </div>
        <div class="form-group">
            <label for="password" class="mt-2">Contraseña:</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($message) : ?>
            <div class='alert alert-danger mt-3 p-1 text-center' role='alert'>
                <?= $message ?>
            </div> 
        <?php endif ?>
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-4">Iniciar Sesión</button>
        </div>
    </div>
    </form>
</div>


<?php require 'templates/partials/footer.phtml' ?>


