<?php require 'templates/partials/header.phtml'; ?>

 <div class="form-container">
    <form action="<?= $action === 'create-product' ? $action : $action . '?product-id=' . (isset($product) ? $product->product_id : '') ?>" method="POST" enctype="multipart/form-data">
        <label for="name">Product Name:</label>
        <input type="text" name="name" id="name" value="<?= isset($product) && isset($product->name) ? $product->name : '' ?>"><br><br>

        <label for="description">Product Description:</label>
        <textarea name="description" id="description"><?= isset($product) && isset($product->description) ? $product->description : '' ?></textarea><br><br>

        <label for="price">Price:</label>
        <input type="number" name="price" id="price" step="0.01" value="<?= isset($product) && isset($product->price) ? $product->price : '' ?>"><br><br>

        <label for="brand">Brand:</label>
        <input type="text" name="brand" id="brand" value="<?= isset($product) && isset($product->brand) ? $product->brand : '' ?>"><br><br>

        <label for="category">Category:</label>
        <select name="category" id="category">
            <?php foreach ($categories as $category) : ?>
                <option value="<?= $category->category_id ?>" <?= (isset($product) && isset($product->category_id) && $product->category_id == $category->category_id) ? 'selected' : '' ?>>
                    <?= $category->category?>
                </option>
            <?php endforeach; ?>
        </select>


        <label for="stock">Stock:</label>
        <input type="number" name="stock" id="stock" value="<?= isset($product) && isset($product->stock_quantity) ? $product->stock_quantity : '' ?>"><br><br>

        <label for="image">Product Image:</label>
     
        <input type="file" required name="image" id="image" accept="image/*" required><br><br>

        <input type="submit" value="Submit Product">
    </form>
</div>
 
<?php require 'templates/partials/footer.phtml'; ?>
