<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./styles/main.css">
    <link rel="stylesheet" href="./styles/card.css">
    <title>Ecommerce</title>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="navbar__logo">
                <a href="home" class="navbar__link">Tredz</a>
            </div>
            <ul class="navbar__menu">
                <li class="navbar__item">
                    <a href="home" class="navbar__link">Home</a>
                </li>
                 <li class="navbar__item">
                    <a href="dashboard" class="navbar__link">Dashboard</a>
                </li>
 
                <?php if (!isset($_SESSION['USER_ID'])): ?>
                    <li class="navbar__item">
                        <a href="login" class="navbar__link">Log in</a>
                    </li>
                <?php else : ?>
                        <li class="nav-item">
                    <a href="logout" class="navbar__link">Logout (<?= $_SESSION['USER_USER_NAME'] ?>)</a>
                    </li>
                <?php endif ?>
            </ul>
        </nav>
    </header>
    <main>
